### ISSUE TITLE
License of data is not shown

### ISSUE THREAD

**Issue by klarareder** [OpenEnergyPlatform/examples#11]
As a   user, I want the license of the data (use and distribution) to be displayed   so that I can protect my data on the one hand and not make any mistakes on   the other.

**Comment by christian-rli** [comment]
RequirementSpecificationID=4

**Comment by Bachibouzouk** [comment]
![Metadata-human-readable-format](https://user-images.githubusercontent.com/4399407/63933143-f2be4780-ca58-11e9-93ab-52ac9c89017f.png)

The license is shown in the metadata (would have been nice to have a commit/PR associated to this issue), therefore I close the issue.
