### ISSUE TITLE
Not possible to assign a license to the data

### ISSUE THREAD

**Issue by klarareder** [OpenEnergyPlatform/examples#12]
As a   user I would like to enter the license of the data (use and distribution), so   that I protect my data on the one hand and on the other hand not to make any   mistakes.

**Comment by christian-rli** [comment]
RequirementSpecificationID=5

**Comment by Bachibouzouk** [comment]
![License_user_filling](https://user-images.githubusercontent.com/4399407/63933430-7d9f4200-ca59-11e9-9a3f-f9615f57bf93.png)

By clicking on "edit" under the metadaten title, it is possible to modify the license for the user. Therefore I close the issue.
