### ISSUE TITLE
License information for the Open Energy Academy?

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/examples#163]
I added a [metainformation](https://openenergyplatform.github.io/academy/meta/) page to the OEA. Short info on context, BMWK support logo. We should probably also add a license information here, and maybe also a contact possibility?
What do you think?

I can edit the page and take on suggestions made here.

**Comment by u-mueller** [comment]
Good idea, Yes to all your questions from my side, 
- shall we also add PtJ and all partners? 
- I suggest License information [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/deed.en), but in one of the tutorials there is also [GNU Affero General Public License Version 3 (AGPL-3.0)](https://github.com/openego/data_processing/blob/master/LICENSE), what do you think, @Ludee?
- @han-f do you - as the lead of this one - want to provide your project e-mail: Contact: oedb@oeko.de (if you want you can also use SIROP@iee.fraunhofer.de)

**Comment by han-f** [comment]
> shall we also add PtJ and all partners?

I think the PtJ link is not needed as they manage fr BMWK (but happy to add it if we want to), and I can definitely add all partners.

> @han-f do you - as the lead of this one - want to provide your project e-mail: Contact: [oedb@oeko.de](mailto:oedb@oeko.de) (if you want you can also use [SIROP@iee.fraunhofer.de](mailto:SIROP@iee.fraunhofer.de))

Yes, I can add our Öko-email as contact

**Comment by han-f** [comment]
I added the partners and contact information. However, what about a license? I am unsure now, because all of our trainings and tutorials have individual licenses, so the Academy license itself, what would it apply to exactly?

**Comment by u-mueller** [comment]
Maybe we can use "License: [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/deed.en) if not stated otherwise"

**Comment by Ludee** [comment]
The AGPL is indeed not a good choice. 
We mostly produce texts and images. The jupyters and example codes could be CC0 or MIT.
All contributions are by our consortium (IEE, ÖI, OVGU, RLI)
If you agree I change the license for the repo and code and update the info page.

I do agree to change the licenses of this repo [RLI]
@stap-m @han-f @u-mueller

**Comment by oeko-oep** [comment]
@Ludee - what about the individual training courses that we have now indicated to be cc by 4.0? would we remove the license info there, or would they keep their individual license?
@wingechr - what is your take on a license for the overall OEA?

**Comment by Ludee** [comment]
I would leave the license information for each course and tutorial because the copyright holder are different.
The repo license covers all code and works as a fallback if no specific information is given.
