### ISSUE TITLE
Metadata is not displayed as human-readable text

### ISSUE THREAD

**Issue by klarareder** [OpenEnergyPlatform/examples#17]
As a   user, I would like the metadata to be displayed as human-readable text so   that I can assign my data to the table columns.

**Comment by christian-rli** [comment]
RequirementSpecificationID=24

**Comment by Bachibouzouk** [comment]
![Metadata-human-readable-format](https://user-images.githubusercontent.com/4399407/63933030-bb4f9b00-ca58-11e9-8b85-71d6cb0f9033.png)

This is human readable text, therefore I close the issue

**Comment by Bachibouzouk** [comment]
This was done in https://github.com/OpenEnergyPlatform/oeplatform/pull/441
