### ISSUE TITLE
Feedback course 08: Licensing

### ISSUE THREAD

**Issue by christian-rli** [OpenEnergyPlatform/examples#188]
Please review course 08 : https://openenergyplatform.github.io/academy/courses/08_licensing/
and provide your feedback as comments below. Feedback can include pointing out errors (such as broken links, things that do not work as described) any suggestions for improvements, things that you are expecting from such a course but find they are missing, etc.

In your comment, please make sure to reference the link to the material you're referring to (the courses link to various materials)

**Comment by l-emele** [comment]
There is also an official (however legally not binding) English version of § 60 c UrhG that could be linked: https://www.gesetze-im-internet.de/englisch_urhg/englisch_urhg.html#p0479

**Comment by flohrreija-oeko** [comment]
For further improvement of this course i would suggest two little updates 
1) I would suggest to explain what _tl;drLegal_ is, e.g. The use of tl;drLegal[https://www.tldrlegal.com/license/odc-open-database-license-odbl] (a platform that provides simplified summaries of software licenses to help demystify legal jargon and make software licenses more accessible) is recommended.
2) The link FOSTER portal does not work to me – maybe update it to https://openscience.eu/foster-open-science
