### ISSUE TITLE
Upload course has broken links

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/examples#202]
There are two links that are wrong and need to be fixed: 

https://openenergyplatform.github.io/academy/courses/tutorials/api/OEP-oedialect_upload_from_csv/, should be  https://openenergyplatform.github.io/academy/tutorials/api/OEP-oedialect_upload_from_csv/ 

https://openenergyplatform.github.io/academy/courses/tutorials/api/OEP-oedialect/, should be
https://openenergyplatform.github.io/academy/tutorials/api/OEP-oedialect/ sein.

## Workflow checklist
- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/academy/blob/production/CONTRIBUTING.md)

**Comment by Ludee** [comment]
Fixed the links.

**Comment by han-f** [comment]
thanks a lot!
