### ISSUE TITLE
A good universal example table is missing

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/examples#203]
## Description of the issue

The Academy needs a good example table including metadata.

## Ideas of solution

Use the example table from the OEMetadata repo and improve. 

## Workflow checklist
- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/academy/blob/production/CONTRIBUTING.md)

**Comment by Ludee** [comment]
Comments:

- No Boolean column
- File has semicolon as delimiter
- No values for geometry

**Comment by jh-RLI** [comment]
> Comments:
> 
> * No Boolean column
> * File has semicolon as delimiter
> * No values for geometry

The example csv now includes these updates. I also added the is_active column to the datapackage.json.

**Comment by jh-RLI** [comment]
The table needs to be recreated and data must be reuploaded to the oeplatform
