### ISSUE TITLE
A proper 404 page is missing

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/examples#205]
## Description of the issue

The error page is not nice.
https://openenergyplatform.github.io/academy/tutorials/api/error404

## Ideas of solution

Add a nice 404 page with platipus

## Workflow checklist
- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/academy/blob/production/CONTRIBUTING.md)

**Comment by han-f** [comment]
@wingechr - its an enhancement and not urgent. Is it easy to implement?

**Comment by wingechr** [comment]
I tried to change the template (853230ae5c3b0dc9d6ec7cb84b5ecba21e6347ec) according to the [docs](https://squidfunk.github.io/mkdocs-material/customization/) but it did not work.

I dont want to spend much more time on it so i will close the issue.

Please re-open if you feel it is more important.
