### ISSUE TITLE
Better explain the difference between courses and tutorials

### ISSUE THREAD

**Issue by l-emele** [OpenEnergyPlatform/examples#208]
## Description of the issue

The explanations of courses and tutorials on the start page and is very short. The distinction between those two could be improved.

## Ideas of solution

Describe possible ideas for solution and evaluate advantages and disadvantages.

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/academy/blob/production/CONTRIBUTING.md)

**Comment by han-f** [comment]
I have added some more explanation.
