### ISSUE TITLE
Academy icon links to OEP

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/examples#210]
## Description of the issue

The Academy icon in the navbar links to the OEP, while I would expect it to link to the start page of the OEA
![grafik](https://github.com/OpenEnergyPlatform/academy/assets/36844029/8665957e-0292-4f2d-b3d5-697b54f7ba88)

## Ideas of solution

* Make the Open Energy Academy text clickable to head back to the starting page and change the icon to the OEP icon
* keep the icon as is and link to OEA main page, find another way to link back to OEP
## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/academy/blob/production/CONTRIBUTING.md)

**Comment by jh-RLI** [comment]
Yes that was a decision by @Ludee . I think it would be good to have something like that: 
oep-icon(link to oep)/academy-icon(link to academy home)

If we use such a solution on all our mkdocs-based websites, we can provide a more consistent navigation.
