### ISSUE TITLE
CONTRIBUTING.md not up to date

### ISSUE THREAD

**Issue by vismayajochem** [OpenEnergyPlatform/examples#217]
## Description of the issue

There are multiple errors in the https://github.com/OpenEnergyPlatform/academy/blob/production/CONTRIBUTING.md 

1. At https://github.com/OpenEnergyPlatform/academy/blob/production/CONTRIBUTING.md there is under the section "Types of interaction" a link [Contributor Covenant Code of Conduct](https://github.com/OpenEnergyPlatform/academy/blob/main/CODE_OF_CONDUCT.md). When clicking on that I get an "404 - page not found

Cannot find a valid ref in 

main/CODE_OF_CONDUCT.md" error.
I don't know if the file really doesn't exist or if the link is flawed.

2. Under the topic "Types of interaction" point A. Use: I couldn't find an "USERS.cff" to add my name and personal details.

3. Under the topic "Types of interaction" point B. Comment (Also at different places ind this document.): I couldn't find an "CITATION.cff" to add my name and personal details.

## Steps to Reproduce

1. Click on the link

## Workflow checklist

- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/academy/blob/production/CONTRIBUTING.md)

**Comment by christian-rli** [comment]
Thank you for opening the issue. I added the previous authors in the citation.cff

**Comment by christian-rli** [comment]
There is no CODE_OF_CONDUCT.md so I removed the line. @Ludee might want to add the file at a later point and can reintroduce the line then.

**Comment by christian-rli** [comment]
@vismayajochem can you please reread the CONTRIBUTING.md with the applied changes and see if it makes sense to you now? If there are no further issues with this, you can close the issue.
