### ISSUE TITLE
Wrong link in Guidebook

### ISSUE THREAD

**Issue by vismayajochem** [OpenEnergyPlatform/examples#218]
## Description of the issue

Concerning the webpage https://openenergyplatform.github.io/academy/tutorials/99_other/OEP_Research_Data_Publishing_Guidebook/
1. The link to the issues [new issues](https://github.com/OpenEnergyPlatform/template/issues) gives an 404 page not found error. 
2. Under the topic "Introduction" the link to the upload tutarial [upload tutorial](https://github.com/OpenEnergyPlatform/tutorial/blob/develop/upload/OEP_Upload_Process_Data_and_Metadata_oem2orm.ipynb) gives an 404 page not found error.
3. Under 1 Creation of metadata  the link [postgresql datatypes](https://www.postgresql.org/docs/9.5/datatype.html) leads to an old version of the webside.

## Steps to Reproduce

Click on the link.

## Ideas of solution

1. Fix the link. I think https://github.com/OpenEnergyPlatform/academy/issues shoud be the correct one.
2. Also fix the link. Maybe to https://openenergyplatform.github.io/academy/tutorials/02_oep_client/02_client_python_upload/ or the equivalent page on github. 
3. Change link to https://www.postgresql.org/docs/current/datatype.html

## Context and Environment

- Version used:
- Operating system:
- Environment setup and (python) version:

## Workflow checklist

- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/academy/blob/production/CONTRIBUTING.md)

**Comment by jh-RLI** [comment]
https://www.postgresql.org/docs/14/datatype.html
