### ISSUE TITLE
Pictures for Login are not shown in Guidebook - How to Publish Your Data on the OEP 

### ISSUE THREAD

**Issue by vismayajochem** [OpenEnergyPlatform/examples#220]
## Description of the issue
On the Webpage https://openenergyplatform.github.io/academy/tutorials/99_other/OEP_Research_Data_Publishing_Guidebook/#311-login the implemented pictures (<img src=\"images/login.png\"  alt=\"OpenEnergy Platform login\" height=\"100\" width=\"100\" align=\"left\"/>  <br><br> and <img src=\"images/token.png\"  alt=\"OpenEnergy Platform Token\" height=\"400\" width=\"500\" align=\"left\" />) are not shown. It seems like the path of the pictures don't exist.
## Steps to Reproduce

1. Visit Webpage
2.
3.

## Ideas of solution
Correctly implement the pictures in github. 

## Context and Environment

- Version used:
- Operating system:
- Environment setup and (python) version:

## Workflow checklist

- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/academy/blob/production/CONTRIBUTING.md)

**Comment by vismayajochem** [comment]
In the Beginners Guide: How to upload data to the OpenEnergy Platform and initiate the review process https://openenergyplatform.github.io/academy/tutorials/99_other/beginners_guide/#11-register-at-the-openenergy-platform is also an discription on how to register with pictures which are shown. But those pictures don't represent the current design of the actual registration side of OEP. So I wouldn't recomment to use those pictures in the Publishing Guidebook but rather use new ones in both guidebooks.

**Comment by christian-rli** [comment]
Closed by [2d8bd3d](https://github.com/OpenEnergyPlatform/academy/commit/2d8bd3d077299f6f4810a01090efbdf72535baee)
