### ISSUE TITLE
 Open Energy Academy How Upload Your Data and Metadata to the OEP not up to date

### ISSUE THREAD

**Issue by vismayajochem** [OpenEnergyPlatform/examples#222]
## Description of the issue

1. In the second sentence the link [new issues](https://github.com/OpenEnergyPlatform/template/issues) gives an 404 page not found error.
2. In the section Introduction both links ([upload template](https://github.com/OpenEnergyPlatform/tutorial/tree/master/upload/upload_template.ipynb) and [Upload Process Guidebook](https://github.com/OpenEnergyPlatform/tutorial/blob/feature/upload_process_tutorial/upload/OEP_Research_Data_Publishing_Guidebook.ipynb)) don't work either and give a 404 page not found error.
3. In the last section 'Writing metadata to the table' the reader is asked to 'See the Creating tables section' but there is no link implemented to jump to that section. 

## Steps to Reproduce

Click on the links.

## Ideas of solution

1. Implement this URL https://github.com/OpenEnergyPlatform/academy/issues instead.
3. Imolement link to the section.

## Context and Environment

- Version used:
- Operating system:
- Environment setup and (python) version:

## Workflow checklist

- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/academy/blob/production/CONTRIBUTING.md)

**Comment by jh-RLI** [comment]
fixed by 753a9af
