### ISSUE TITLE
OEA Meta page: how to adjust for time after SIROP ends?

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/examples#228]
## Description of the issue

https://openenergyplatform.github.io/academy/meta/
will need to be updated once SIROP comes to an end. 

## Ideas of solution

**Starting from October 2024,** with the end of SIROP and for the time being, Reiner Lemoine Institute will take care of maintainance and act as a contact point. Questions with regard to the Open Energy Academy can be sent to: oep-contact@lists.rl-institut.de

**From 2021-2024**, the Open Energy Academy was developed within the BMWK-funded SIROP project (Förderkennzeichen 03EI1035A-03EI1035D) by [Fraunhofer IEE](https://www.iee.fraunhofer.de/), [Öko-Institut](https://www.oeko.de/), [Otto von Guerike Universität Magdeburg](https://www.inf.ovgu.de/) and [Reiner Lemoine Institut](https://reiner-lemoine-institut.de/).

@stap-m @wingechr @christian-rli @jh-RLI what do you think? Do you have suggestions?

## Workflow checklist

- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/academy/blob/production/CONTRIBUTING.md)

**Comment by christian-rli** [comment]
I like the proposed temporal outline. What makes the 'from 2024' section difficult is that whatever we decide to communicate there, depends on things that haven't been decided yet. RLI can be a contact point and contributor without a project like SIROP which directly funds the academy, but I don't know about ÖI or OvGU. RLI is free to interpret this as part of their NFDI tasks, which is in our interest and therefore, I think, also the most likely thing to happen.

I would like to avoid a situation in which RLI is the only institution to continue maintaining this jointly developed page, but it's a possibility if necessary.

**Comment by han-f** [comment]
@christian-rli  - could you please make a proposal for the text Starting from October 2024: ### as we discussed in the project meeting? I can then implement.

**Comment by christian-rli** [comment]
@han-f I phrased a very concise bullet point that I think should suffice. Feedback welcome. As a contact address I would like to use oep-contact@lists.rl-institut.de. Currently this will also forward to you and @stap-m but you are free to unsubscribe from mails to this address, if it seems appropriate at a later point in time.

**Comment by han-f** [comment]
@christian-rli - this reads good to m and I am also fine with being included in the email address, have done so above. Is it ok like this?

**Comment by han-f** [comment]
I have updated the meta page accordingly.
