### ISSUE TITLE
Feedback on:  OEP Client Tutorial 02 - Upload data to the Open Energy Platform using the OEP Client in a python script

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/examples#236]
Please provide feedback on the tutorial https://openenergyplatform.github.io/academy/tutorials/02_oep_client/02_client_python_upload/ in comments below. Feedback can include pointing out errors (such as broken links, things that do not work as described) any suggestions for improvements, things that you expected but missed, etc.

**Comment by han-f** [comment]
from @flohrreija-oeko: 
Some general comments on all oepclient tutorials:

I would suggest to the add the feedback link to this issue both at the beginning and in the about section of the tutorial (
The code did not work (understandably) until i was a member of the OEP group in GitHub, it could be added as a requirement for clarity

Comments on 01_client_python_download.ipynb

It also (see first comment of the issue) took me some time to understand that "tutorial_example_table" is an already existing table in model_draft - either a hint on this in the comments of the code or e.g. a codeline to get the url where the table is located (also to verify if everything worked) would be great!

Comments on 02_client_python_upload.ipynb

Here as well (again as first comment) I think it is super important to be able to access the URL of the created table to verify while doing the tutorial.

If I understand correctly in Section "upload data" we use an existing dataset in the OEP (in this case "tutorial_example_table) to upload data into the table we just created - normally the data to be uploaded would not come from an existing dataset in the OEP but from e.g. an Excel or textfile. I think it should be clarified how to upload the data from there as well using the OEPClient (either through linking to section 2.1.2 of the [Beginners Guide](https://openenergyplatform.github.io/academy/tutorials/99_other/beginners_guide/) or by including a similar example code in the OEP Client tutorial 02).

**Comment by wingechr** [comment]
> It also (see first comment of the issue) took me some time to understand that "tutorial_example_table" is an already existing table in model_draft - either a hint on this in the comments of the code or e.g. a codeline to get the url where the table is located (also to verify if everything worked) would be great!

No, not really. this table is for the download tutorial. for the upload tutorial, the user creates a new table in the sandbox.

> If I understand correctly in Section "upload data" we use an existing dataset in the OEP (in this case "tutorial_example_table) to upload data into the table we just created - normally the data to be uploaded would not come from an existing dataset in the OEP but from e.g. an Excel or textfile. I think it should be clarified how to upload the data from there as well using the OEPClient (either through linking to section 2.1.2 of the [Beginners Guide](https://openenergyplatform.github.io/academy/tutorials/99_other/beginners_guide/) or by including a similar example code in the OEP Client tutorial 02).

No, the data comes from a static file from the academy website, not from a table on the oep
