### ISSUE TITLE
Write embargo tutorials

### ISSUE THREAD

**Issue by vismayajochem** [OpenEnergyPlatform/examples#242]
## Description of the issue

There is no documentation for the embargo area. 

## Ideas of solution

Write/change tutorials:
Since there is the seperation between the API, the OEP Client and the wizard for the upload/download tutorials, we want to keep that seperation and 

- [ ] include the option of an embargo in the [API tutorial for the upload process](https://openenergyplatform.github.io/academy/tutorials/01_api/02_api_upload/)  and
- [ ] include the option of an embargo in the OEP client tutorials using the OEP CLIENT for the upload process [with python](https://openenergyplatform.github.io/academy/tutorials/02_oep_client/02_client_python_upload/) and [with command line](https://openenergyplatform.github.io/academy/tutorials/02_oep_client/04_client_cli_upload/)
- [ ] include the option of an embargo in the [wizard tutorial](https://openenergyplatform.github.io/academy/tutorials/99_other/wizard/)
And since there is no seperate tutorial describing the publishing process (only the [guidebook](https://openenergyplatform.github.io/academy/tutorials/99_other/OEP_Research_Data_Publishing_Guidebook/) which is not up to date) we want to write a

- [ ] how to publish tutorial including the option of an embargo

## Workflow checklist

- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/academy/blob/production/CONTRIBUTING.md)

**Comment by vismayajochem** [comment]
Pls check the first draft of the tutorial on the publishing process, feedback is very welcome! Things where I was unsure are commented in German and marked with a ? .

**Comment by jh-RLI** [comment]
I added a review to the pull request :)
