### ISSUE TITLE
[metadata] Evaluate and discuss OSE metadata recommendations

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/examples#25]
PROJECT: OPEN SOURCE ENERGIEWENDE
Recommended metadata for a dataset:

Name | A name   or a short description of this dataset.
-- | --
ID | A   globally unique identifier, e.g. Universal Unique Identifiers (UUID) and Digital   Object Identifiers (DOI).
Homepage | A URL   for the home on the web that is related to this dataset (“landing page”). The   URL should be permanent.
Licenses | The   license(s) under which the dataset is provided as name, URL and SPDX   identifier, such as: Creative Commons Zero, https://creativecommons.org/publicdomain/zero/1.0/   , CC0-1.0).
Description | A   description of the dataset. Depending on type and size this can be anything   from one paragraph to several pages.
Documentation | A link   to the further documentation of the dataset
Geographic   scope | Specify   the geographical area this dataset represents, e.g. “50hertz control zone”
Temporal   scope | Specify   the beginning and end of the total period covered by this dataset, e.g. “2008-01-01T00:00:00   to 2018-05-04T:23:59:59”
Unit | The unit   of measurement, e.g. “MW”.
Publication   date | The   publishing date of the data package, such as 2018-04-05.
Sources | The raw   sources for this dataset. Where the publishinger of this dataset is not the   original creator of the data, proper reference should be given to the   original source. For example, in the case of the ENTSO-E Transparency   Platform, the contact details of the Primary Data Owner(s) as well as the   Data Provider(s) should be provided.
Contact | A point   of contact, such as a forum, or ideally a person available to contact for   questions and feedback regarding the data.
Technical   specifications | Information   required to parse the data file(s) in the processing software, i.e. for CSV   files the character encoding (i.e. “UTF8”), the columns separator (i.e. “,”)   and decimal character (i.e. “.”). For time series data the format of datetime   values (i.e.”YYYY-MM-DDThh:mm:ssZ”)
Time-resolution | For time   series data, indicate the duration between time steps as well as whether data   is associated with the beginning or end of a reported period.
Metadata for each variable (e.g., one column in a table of time series   data or one attribute in a list of powerplants)
Name | This   property should correspond to the name of the column in the data file. As   such it should be unique.
Description | A   description for this column.
Unit | The unit   of measurement, e.g. MW.
Type | Indicate   data type (e.g. ”string”, ”number”, ”datetime”) and format of this column,   e.g. for a datetime ”YYYY-MM-DDThh:mm:ssZ”
Geographical   scope | For time   series data, specify the geographical area this column represents, e.g. “50Hertz   control area”.
Temporal   scope | For time   series data, specify the beginning and end of the total period covered by   this column, e.g. 2008-01-01T00:00:00 to 2018-05-04T:23:59:59..

**Comment by Ludee** [comment]
[Comparison and discussion sheet](https://docs.google.com/spreadsheets/d/13oF2RkyjiMmI93USMn8YNTsj6xiH6EIM6SHXvEoJMD8/edit#gid=1058893251)

**Comment by christian-rli** [comment]
This was considered during the creation of metadata standard 1.4.0 . With its release, can we close this issue @Ludee
