### ISSUE TITLE
[metadata] Collect ideas and feedback for next metadata version

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/examples#32]
There will be a next metadata version (**v1.4**) for the OEP.
The current version is **v1.3**.

This issue will be used to collect metadata feedback.

- [x] include open license (PD) for the metadata (see [openmod forum](https://forum.openmod-initiative.org/t/public-domain-pd-license-for-metadata/533/6))
- [x] change language entries to (see [openmod forum thread](https://forum.openmod-initiative.org/t/breakout-group-about-metadata/108))
- [x] tags/ keywords must be included
- [x] add unique identifier
- [x] check and include [GO FAIR Principles](https://www.go-fair.org/fair-principles/)
- [x] include info about data review (Link to issue, Reviewer, see https://github.com/OpenEnergyPlatform/data-preprocessing/issues/2 )

**Comment by Ludee** [comment]
v1.4 was missing the foreignKey. I forgot to reference this issue in the hotfix: 8a68e4d5a48f2cefefdde9e1640aafdbb8c72fa2

**Comment by Ludee** [comment]
In addition to "context", we need to add two fields for the founding agency and a link to the logo:

Suggestion:

**fundingAuthority**
**fundingAuthorityLogo**

Example:

`"fundingAuthority": "Gefördert durch das Bundesministerium für Wirtschaft und Energie (BMWi)."`
or `"fundingAuthority": "Bundesministerium für Wirtschaft und Energie (BMWi)."`
`"fundingAuthorityLogo": "https://reiner-lemoine-institut.de/wp-content/uploads/2016/10/BMWi.jpg"`

In addition, the OEP should display the image if it is a valid link:
![BMWi logo](https://reiner-lemoine-institut.de/wp-content/uploads/2016/10/BMWi.jpg)

**Comment by christian-rli** [comment]
I like your suggestions @Ludee 
> **fundingAuthority**
> **fundingAuthorityLogo**

, but I would prefer fundingAgency and fundingAgencyLogo, respectively - it just sounds less authoritatian :)

**Comment by Ludee** [comment]
Good point. 

`"fundingAgency": "Bundesministerium für Wirtschaft und Energie (BMWi)."`
`"fundingAgencyLogo": "https://www.innovation-beratung-foerderung.de/INNO/Redaktion/DE/Bilder/Titelbilder/titel_foerderlogo_bmwi.jpg?__blob=poster&v=2"`

And I found an official source of the image:

![BMWi logo](https://www.innovation-beratung-foerderung.de/INNO/Redaktion/DE/Bilder/Titelbilder/titel_foerderlogo_bmwi.jpg?__blob=poster&v=2)

**Comment by klarareder** [comment]
I also prefer fundingAgency

**Comment by christian-rli** [comment]
closed with #58
