### ISSUE TITLE
Metadata 1.4 Release

### ISSUE THREAD

**Issue by christian-rli** [OpenEnergyPlatform/examples#57]
In order to finalize metadata version 1.4, we still need to address a few things. I changed the examples according to our discussion last week. A list of things that we have to finally agree on:

- [x] none -> null ( #54 ) 
- [x] fundingAgency and fundingAgencyLogo ( #32 Do you agree with my changes? )
- [x] timestamps (suggestion in #22 )
- [x] license ids ( #55 )
- [x] "" values in template -> all to null?
- [x] publisherLogo (who's the publisher? will it an extra key? )

Feel free to add issues to this list, in case I forgot them. 

Once we've agreed on everything we can merge the 1.4 branch into master and declare it the final version 1.4. (By the way, I'd argue against calling it version 1.4.1, because I believe it will lead to more confusion down the road than necessary, especially when there is no real version 1.4).

**Comment by christian-rli** [comment]
I pushed my commits for this issue into a new branch v1.4_release. Latest change is this one: https://github.com/OpenEnergyPlatform/examples/commit/1d035d2db86f820906690efd5b86c2347e19b37e

**Comment by christian-rli** [comment]
Our template file is not consistent - neither within itself nor with our own requirements. Most values are "", but not all are. Some are "null" and some have actual strings. Why is that and shouldn't it be consistently "null", except for the fields we actually do require?

**Comment by christian-rli** [comment]
Have a look at [this file](https://github.com/OpenEnergyPlatform/examples/blob/v1.4_release/metadata/oep_metadata_example.json). If there are no complaints it will end up defining the structure of metadata version 1.4.
@MGlauer let me know if you agree to @Ludee 's comments in #55

**Comment by MGlauer** [comment]
There is also my remark from #54. It should not be `"null"` but `null`.

**Comment by christian-rli** [comment]
closed with #58
